# Exception

예상하거나 예상치 못한 일이 발생할 것을 미리 예건하고 안전장치를 하는 것

## try ... catch() 구문

```java
try {
    if(조건) {
        throw new Exception("Number is over");
    }
} catch (Exception e) {

}
```

## try ... catch() ... finally

finally 내에 코드는 무조건 실행된다.

catch 블록의 순소는 중요하다.

## 모든 예외의 부모 클래스는 java.lang.Exception

## 모든 예외의 할아버지는 java.lang.Throwable

- `getMessage()` : 예외 메시지를 String 형태로 제공한다.
- `toString()` : 예외 메시지를 String 형태로 제공하지만, 예외 클래스 이름도 같이 제공한다.
- `printStackTrace()` : 첫 줄에 예외 메세지를 출력하고 예외 발생 메소드들의 호출 관계를 출력

## 예외의 종류

- checked Exception : error와 런타임 예외를 제외한 모든 예외
- error : 자바 프로그램 밖에서 일어나는 예외
- runtime Exception : 런타임 예외라고 불리며 컴파일 체크를 하지 않는다

## 예외를 만들어 보자

```java
public class CustomException {
    public static void main(String args[]) {
        CustomException sample = new CustomeException();
        try {
            sample.throwMyException(13);
        } catch (MyException mye) {
            mye.printStackTrace();
        }
    }

    public void throwMyException(int number) throws MyException {
        try {
            if(number > 12) {
                throw new MyException("Number is over than 12");
            }
        } catch(MyException e) {
            e.printStackTrace();
        }
    }
}

public class MyException extends Exception {
    public MyException() {
        super();
    }
    public MyException(String message) {
        super(message);
    }
}
```

